polymerAbreDict = {
    "ABA": "Acrylonitrile Butadiene Acrylate",
    "ABAK": "Acrylonitrile Butadiene Acrylate",
    "ABS": "Acrylonitrile Butadiene Styrene",
    "ABS + PUR": "Blend of Acrylonitrile Butadiene Styrene and Polyurethane",
    "ABS / PVC": "Acrylonitrile Butadiene Styrene / Polyvinyl Chloride",
    "ACS": "Acrylonitrile Chlorinated Polyethylene Styrene",
    "AES": "Acrylonitrile Ethylene-Propylenediene Styrene",
    "AMA": "Acrylate Maleic Anhydride Terpolymer",
    "AMMA": "Acrylonitrile Methyl Methacrylate",
    "APO": "Amorphous Polyolefin",
    "AS": "Acrylonitrile Styrene",
    "ASA": "Acrylonitrile Styrene Acrylate",
    "ASA + PC": "Blend of Acrylonitrile Styrene Acrylate and Polycarbonate",
    "BMC": "Bulk Molding Compound",
    "BMI": "Bis Maleimide",
    "BR": "Butadiene Rubber",
    "CA": "Cellulose Acetate",
    "CAB": "Cellulose Acetate Butyrate",
    "CAP": "Cellulose Acetate Propionate",
    "CF": "Cresole-Formaldehyde",
    "CMC": "Carboxylmethyl Cellulose",
    "CN": "Cellulose Nitrate (Celluloid)",
    "COC": "Cycloolefin Copolymer",
    "COP": "Copolyester Thermoplastic Elastomer",
    "CP": "Cellulose Propionate",
    "CPE": "Chlorinated Polyethylene",
    "CPVC": "Chlorinated Polyvinyl Chloride",
    "CSF": "Casein-Formaldehyde",
    "CTA": "Cellulose Triacetate",
    "CTFE": "Chlorotrifluoroethylene",
    "DAP": "Diallyl Phthalate (Thermoset)",
    "EAA": "Ethylene Acrylic Acid Copolymer",
    "EBA": "Ethylene Butylacetate",
    "ECTFE": "Ethylene Chlorotrifluoroethylene",
    "EEAK": "Ethylene Ethylacrylate",
    "EMA": "Ethylene Methacrylic Acid",
    "EMAA": "Ethylene Methacrylic Acid Copolymer",
    "EMAC": "Ethylene Methyl Acrylate Copolymer",
    "EP": "Ethylene Propylene",
    "EPDM": "Ethylene Propylene Diene Monomer Rubber",
    "EPM": "Ethylene Propylene Copolymer Rubber",
    "EPR": "Ethylene Propylene Rubber",
    "EPS": "Expandable Polystyrene",
    "ESBR": "Emulsion Styrene Butadiene Rubber",
    "EVA": "Ethylene Vinyl Acetate",
    "EVOH": "Ethylene Vinyl Alcohol",
    "FEP": "Fluorinated Ethylene Propylene",
    "FF": "Furan-Formaldehyde",
    "FRP": "Fibre Reinforced Plastic",
    "GPPS": "General Purpose Polystyrene",
    "HDPE": "High Density Polyethylene",
    "HIPS": "High Impact Polystyrene",
    "HMC": "High Strength Molding Compound",
    "HMWHDPE": "High Molecular Weight High Density Polyethylene",
    "ION": "Ionomer",
    "IPN": "Interpenetrating Polymer Network",
    "LCP": "Liquid Crystal Polymer",
    "LDPE": "Low Density Polyethylene",
    "LPE": "Linear Polyethylene",
    "MA": "Maleic Anhydride",
    "MABS": "Methylmethacrylate Acrylonitrile Butadiene Styrene",
    "MBS": "Methacrylate Butadiene Styrene",
    "MC": "Methyl Cellulose",
    "MDPE": "Medium Density Polyethylene",
    "MF": "Melamine Formaldehyde",
    "MP": "Melamine Phenolic",
    "MPF": "Melamine Phenol-Formaldehyde",
    "NBR": "Nitrile Butadiene Rubber",
    "OSA": "Olefin Modified Styrene Acrylonitrile",
    "P": "Phenolic",
    "PA": "Polyamide",
    "PA 11": "Polyamide 11",
    "PA 12": "Polyamide 12",
    "PA 46": "Polyamide 46",
    "PA 6": "Polyamide 6",
    "PA 66": "Polyamide 66",
    "PBT": "Polybutylene Terephthalate",
    "PC": "Polycarbonate",
    "PE": "Polyethylene",
    "PEEK": "Polyetheretherketone",
    "PEI": "Polyetherimide",
    "PEN": "Polyethylene Naphthalate",
    "PET": "Polyethylene Terephthalate",
    "PF": "Phenol-Formaldehyde",
    "PI": "Polyimide or Polyisoprene",
    "PLA": "Poly Lactic Acid",
    "PMMA": "Polymethyl Methacrylate",
    "POM": "Polyoxymethylene (Acetal)",
    "PP": "Polypropylene",
    "PPE": "Polyphenylene Ether",
    "PPS": "Polyphenylene Sulfide",
    "PS": "Polystyrene",
    "PTFE": "Polytetrafluoroethylene",
    "PU": "Polyurethane",
    "PVC": "Polyvinyl Chloride",
    "SAN": "Styrene Acrylonitrile",
    "SBR": "Styrene Butadiene Rubber",
    "SEBS": "Styrene Ethylene Butylene Styrene",
    "SIS": "Styrene Isoprene Styrene",
    "SMA": "Styrene Maleic Anhydride",
    "SMC": "Sheet Molding Compound",
    "TPE": "Thermoplastic Elastomer",
    "TPU": "Thermoplastic Urethane",
    "UHMWPE": "Ultra High Molecular Weight Polyethylene",
    "VLDPE": "Very Low Density Polyethylene",
    "XLPE": "Crosslinked Polyethylene"
}
